apiVersion: v1
kind: Pod
metadata:
  name: spark-test
  namespace: spark
spec:
  restartPolicy: Never
  containers:
  - name: spark
    image: apache/spark:3.5.5-java17-python3  # Image có Python3 support
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash"]
    args: ["-c", "sleep infinity"]
    securityContext:
      runAsUser: 0
    volumeMounts:
    - name: script-volume
      mountPath: /mnt
  volumes:
  - name: script-volume
    hostPath:
      path: /mnt/data/spark
      type: DirectoryOrCreate

---